version: "3.8"

services:
  web:
    build: ./fastapi_app
    ports:
      - "8000:8000"
    #command: bash -c 'cd /fastapi_app/ && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    command: bash -c 'cd /fastapi_app/ && alembic revision -m 'check' && alembic upgrade head  && uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
    depends_on:
      - db

  db:
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foo
